### ISSUE TITLE
Error: ValueError: Cannot feed value of shape (64,) for Tensor 'x:0', which has shape '(?, 128, 128, 3)'

### ISSUE THREAD

**Issue by jialongge** [satyenrajpal/Concrete-Crack-Detection#13]
Hi, I faced this error when I ran Train_CD.py.

![image](https://user-images.githubusercontent.com/28819576/50007426-d756fd80-ffeb-11e8-8200-82c8ce05c7ae.png)

I attempted several methods reshaping or resizing the numpy arrays or the tensors:
![image](https://user-images.githubusercontent.com/28819576/50007446-eb9afa80-ffeb-11e8-8ec8-441521d9f3d7.png)
But it just gives me different errors.

Would really appreicate any help and I am pretty new to tensorflow and machine learning!

Thank you!

**Comment by jialongge** [comment]
Hi all,
the problem is solved. The problem was that I didnt resize my input images to 128*128pixels, which i subsequently did using a PIL script. After which i still encountered the problem, but it was cos there was a cache file my_datase_cache.pkl that doesnt overwrite itself everytime my script is run. So after i manually deleted that cache file and rerun my script, it works!

**Comment by satyenrajpal** [comment]
Thanks for the update!
