### ISSUE TITLE
Check Point Directory does not exist

### ISSUE THREAD

**Issue by pedrohgouvea** [satyenrajpal/Concrete-Crack-Detection#14]
Hi, I'm having some troubles to run the Running.py

I'm receiving the message "SystemExit: Check Point Directory does not exist", I have the checkpoint file. Should I create the folder?

**Comment by jialongge** [comment]
not totally sure what is the issue, but do take note that the --meta_file argument is up till the file name("--meta_file C:\.......\meta_files\model_complete.meta") while --CP_dir is till the folder that contains the CP("--CP_dir C:\......\meta_files")

**Comment by pedrohgouvea** [comment]
Sorry if my explanation was not so good. Well, my current code is like this below and my folder does not have the folder meta_files as you can see in the print.

I'm not sure what's wrong I am doing.

```
    def parse_arguments():
        parser = argparse.ArgumentParser(description='Testing Network')
        parser.add_argument('--in_dir',dest='in_dir',type=str,default='cracky_test')
        parser.add_argument('--meta_file',dest='meta_file',type=str,default='model_complete.meta')
        parser.add_argument('--CP_dir',dest='chk_point_dir',type=str,default='CURRENT_DIR')
        parser.add_argument('--save_dir',type=str,default=os.getcwd())
        return parser.parse_args()
```

![folder](https://user-images.githubusercontent.com/8716707/52383516-1de14980-2abd-11e9-8e3d-b6a533a6cf09.jpg)

**Comment by pedrohgouvea** [comment]
Thanks, I could manage it. However, now I don't see any output result, I only receive this message on the console and nothing else.

> runfile('C:/Users/pedro/Desktop/Concrete-Crack-Detection-master/Running.py', wdir='C:/Users/pedro/Desktop/Concrete-Crack-Detection-master')
> - Data loaded from cache-file: my_dataset_cache_test.pkl
> INFO:tensorflow:Restoring parameters from C:\Users\pedro\Desktop\Concrete-Crack-Detection-master\model_complete

**Comment by satyenrajpal** [comment]
@pedrohgouvea , the output result is stored in `--save dir` argument (default: current working directory). The file name should be outfile_{}.jpg

**Comment by pedrohgouvea** [comment]
Hi @satyenrajpal , I checked but I don't have any output stored in my save directory, I tried to change the code to see if I would get the file but I didn't.

So my current code and my folder look like as below. If possible could you see if I made any mistakes?

![untitled](https://user-images.githubusercontent.com/8716707/52606561-667e7580-2eb6-11e9-8482-4311bdfe4289.jpg)
