### ISSUE TITLE
PyTorch: IndexError

### ISSUE THREAD

**Issue by lookseelooksee** [satyenrajpal/Concrete-Crack-Detection#28]
Hi satyenrajpal,
I have tried the version from master and it works! When i tried the pytorch version, i have the error:
IndexError: dimension specified as 0 but tensor has no dimensions
when I input:  python3 main.py --mode train --save_dir output into terminal

**Comment by Majdi1994** [comment]
Hi Sir,

Hope this message finds you well.

Can you please help me to find the steps that I need to implement in order to run the master version properly. since you already did that.

I appreciate your help! 

Look forward to hearing from you.

Best regards.

Majdi Flah

**Comment by satyenrajpal** [comment]
@lookseelooksee , can you paste the complete set of commands?

**Comment by lookseelooksee** [comment]
Hello @Majdi1994 
For Train_CD.py:
python Train_CD.py --in_dir cracky --iter 1500 --save_folder output
--> store your data in cracky folder
--> sends finished model to output folder

For running.py:
python Running.py --in_dir cracky_test --meta_file output/model_complete.meta --CP_dir output --save_dir crack
--> store your test images in cracky_test folder
--> saves the output in crack folder

That is how i ran it.

**Comment by lookseelooksee** [comment]
Hello @satyenrajpal
I have managed to run it.

**Comment by 8977785855** [comment]
Hi @Majdi1994 , @satyenrajpal 
Facing same issue " Index Error " with PyTorch version.
