### ISSUE TITLE
error: missing 'in_dir' and 'save_folder'

### ISSUE THREAD

**Issue by rafaa1988** [satyenrajpal/Concrete-Crack-Detection#3]
Hi all,
I've put the dataset (cracky) folder in the os directory.
After downloading and running the Train_CD.py without error, I ran Running.py and got the following Error:
TypeError: __init__() missing 2 required positional arguments: 'in_dir' and 'save_folder'

**Comment by satyenrajpal** [comment]
Hi! I've made the changes, there was a small mixup between different versions. It should run fine now. Let me know otherwise

**Comment by guangxiyzy** [comment]
Hi,rafaa1988 .
   Could you tell me what's version of tensorflow you used?
