### ISSUE TITLE
cracky_test missing in dataset

### ISSUE THREAD

**Issue by JonasMie** [satyenrajpal/Concrete-Crack-Detection#6]
Hey @satyenrajpal,

thanks for sharing your project on concrete crack detection! Awesome work!
I just cloned the project and played around with it a little bit and training seems to work fine!
But when it comes to making predictions, I'm missing the images that you described to be in the cracky_test folder.
Did I miss something or are they not contained in the dataset that you provided in issue #2. 

Thanks!
Jonas

**Comment by satyenrajpal** [comment]
Hi @JonasMie, I have not provided those images. It's up to you what images you want to put in that folder.

**Comment by JonasMie** [comment]
Thanks for your answer @satyenrajpal! Good to know, that's also what I did now.
